### ISSUE TITLE
maintainers: spelling of policies 

### ISSUE THREAD

**Issue by SergeCroise** [OpenRailAssociation/project-template#1]
An **"i"** is missing in the word _policies_ in the files
GOVERNANCE.md (... all Project policies ...)
and  
MAINTAINERS.md (... to abide by all of the Organization's policies, ...)
as well as in the new project 
https://github.com/OpenRailAssociation/dac-migration-dss

Is it necessary to open an issue in dac-migration-dss
or just create pull requests in this project (template) and dac-migration-dss ?
@cornelius  @frederik-db , please review!

(see also
https://github.com/OpenRailAssociation/technical-committee/commit/9eabc7ead5791cdf9292c12a7dde7acfe76d987f 
and
https://www.merriam-webster.com/dictionary/policies )

**Comment by cornelius** [comment]
Feel free to open pull requests for the repos, no need to create issues first.
